### PR TITLE
Bump to 0.2.0

### PR DESCRIPTION
**Pull request by esteve**
This PR updates version number to 0.2.0 in preparation for a new release.

### CODE REVIEW

**Comment by luca-della-vedova** [comment]
Should we put this on hold until we know how to distribute `cargo-ament-build` on packagecloud?

**Comment by esteve** [comment]
@luca-della-vedova I think it's safe to merge this PR as it'll streamline the installation process for the extension and the cargo plugin now that the plugin is available via PyPI (i.,e. we can just pip install the extension and the plugin will be installed as well)

**Review by luca-della-vedova — APPROVED** [review]

**Comment by luca-della-vedova** [comment]
Imho it would be great to get https://github.com/colcon/colcon-ros-cargo/pull/31 in before this, so we can have a graceful failure where we tell the user what to do if `cargo-ament-build` is not installed and we can release this and `colcon-cargo` on packagecloud

**Comment by esteve** [comment]
@luca-della-vedova good idea, I waited until #31 was merged, I'll merge this now. Thanks!

**Pull request merged**
