### PR TITLE
Depend on the cargo-ament-build Python wheel

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by esteve** [comment]
This should fail now because the `cargo-ament-build` PyPI wheel is not uploaded yet.

**Comment by luca-della-vedova** [comment]
If we are installing `cargo-ament-build` from Pypi, should we remove the action step that installs it manually from cargo?

**Comment by esteve** [comment]
@luca-della-vedova yeah, that makes sense

**Comment by esteve** [comment]
@luca-della-vedova whoa, maturin is magic:

https://pypi.org/project/cargo-ament-build/

**Comment by esteve** [comment]
Looks like CI is failing because the `cargo-ament-build` wheel is only available for Python 3.8+ and the `colcon` CI requires Ubuntu 20.04 and Python 3.6 for one of the targets. @cottsay is  there a way to provide a custom `strategy.json` file or should I just override the matrix.os? I tried putting a `stategy.json` file in different places but it doesn't seem to work. Thanks

**Comment by luca-della-vedova** [comment]
Hi @esteve

This is really good stuff, thanks a lot! We can use `matrix-filter` for that purpose, I opened a [PR](https://github.com/esteve/colcon-ros-cargo/pull/1) to your branch that introduces it to remove Ubuntu 20.04, it also removes the vendored action since it was introduced purely to install `cargo-ament-build` through cargo, but this is not needed anymore so we can just rely on the upstream workflow.
You need to approve my action to your repo since I'm a first time contributor, but a [run of that branch on my own fork](https://github.com/luca-della-vedova/colcon-ros-cargo/pull/3) shows green CI and Ubuntu 20.04 being skipped so I'm pretty confident it will be ok

**Comment by esteve** [comment]
@luca-della-vedova awesome, thank you!

**Review by luca-della-vedova — APPROVED** [review]

**Pull request merged**
